apiVersion: v1
kind: Service
metadata:
  name: rest-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    service: rest-service
