name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
permissions: write-all


jobs:
  verify-project-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Spring Boot build with Skaffold
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17.0
          distribution: 'adopt'
          java-package: 'jdk'

      - name: Check Maven Version
        run: mvn --version

#      - name: Build project and run Integration tests
#        working-directory: ./rest-endpoint-application
#        run: mvn clean verify

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images with Skaffold
        uses: hiberbee/github-action-skaffold@1.24.0
        with:
          command: build
          working-directory: ./rest-endpoint-application